#!/usr/bin/env bash
SRCDIR=/.bash
SRCFILES=".bashrc .bash_aliases .hgrc .vimrc .bashrc.d/prune-kernels"
TGTDIRS="oliver::/home/oliver root:/root"

function cpnew
{
	cp --preserve=timestamps "$1" "$2" && chown $3 "$2"
}

for src in $SRCFILES; do
	for tgtdir in $TGTDIRS; do
		OWNER=${tgtdir%:*}
		TGTDIR=${tgtdir##*:}
		if [[ -f "$SRCDIR/$src" ]]; then
			[[ -L "$TGTDIR/$src" ]] && { echo "Unlinking $TGTDIR/$src and copying new file in"; rm -f "$TGTDIR/$src" && cpnew "$SRCDIR/$src" "$TGTDIR/$src" "$OWNER"; }
			[[ ! -f "$TGTDIR/$src" ]] && { echo "Copying new file $TGTDIR/$src for owner '$OWNER'"; cpnew "$SRCDIR/$src" "$TGTDIR/$src" "$OWNER"; }
			[[ "$SRCDIR/$src" -nt "$TGTDIR/$src" ]] && { echo "Copying newer file $TGTDIR/$src for owner '$OWNER'"; cpnew "$SRCDIR/$src" "$TGTDIR/$src" "$OWNER"; }
		else
			echo "Could not find $SRCDIR/$src for copying ..."
		fi
	done
done
