#!/usr/bin/env bash
# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:
pushd "$(dirname "$0")" > /dev/null 2>&1 && BASEDIR=$(pwd) && popd > /dev/null 2>&1
source $BASEDIR/.bashrc.d/refresh-dotfiles
# Clean old stuff
OBSOLETE_FILES=(musl-gcc)
for i in "${OBSOLETE_FILES[@]}"; do
	test -f "$BASEDIR/.bashrc.d/$i" && rm -f "$BASEDIR/.bashrc.d/$i"
done
unset OBSOLETE_FILES
refresh-dotfiles "$@"
