#!/usr/bin/env bash
[[ -n "$TGTDIR" ]] || TGTDIR="$HOME"
# Only on Debian/Ubuntu
if [[ -e "/etc/debian_version" ]]; then
	if [[ ! -e "$TGTDIR/.selected_editor" ]]; then
		VIM=$(which vim.nox)
		if [[ -n "$VIM" ]]; then
			echo "SELECTED_EDITOR=\"$VIM\""|tee "$TGTDIR/.selected_editor"
		fi
	fi
	SSH_VER=$(ssh -V 2>&1|grep -oE '^OpenSSH_[[:digit:]]+\.[[:digit:]]+'|grep -oE '[[:digit:]]+\.[[:digit:]]+')
	if [[ -n "$SSH_VER" ]]; then
		SSH_MINVER=${SSH_VER##*.}
		SSH_MAJVER=${SSH_VER%%.*}
		SSH_NUMVER=$((SSH_MINVER + SSH_MAJVER * 1000))
		# Depending on the SSH version, use a ProxyCommand based on netcat (nc) or ssh itself.
		if ((SSH_NUMVER >= 5004)); then
			echo "SSH_VER = $SSH_VER; SSH_MINVER = $SSH_MINVER; SSH_MAJVER = $SSH_MAJVER; SSH_NUMVER = $SSH_NUMVER"
		fi
	fi
fi
