#!/usr/bin/env bash
# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:
# shellcheck shell=bash disable=SC2154,SC2219

function ducks
{
	if [[ $- == *i* ]]; then
		declare -A _colors=(
			[cR]='\e[1;31m'  [cG]='\e[1;32m'  [cB]='\e[1;34m'
			[cR_]='\e[0;31m' [cG_]='\e[0;32m' [cB_]='\e[0;34m'
			[cW]='\e[1;37m'  [cY]='\e[1;33m'
			[cW_]='\e[0;37m' [cY_]='\e[0;33m'
			[cZ]='\e[0m'
		)
		for _k in "${!_colors[@]}"; do
			  declare -p "$_k" &>/dev/null || local "$_k"="${_colors[$_k]}"
		done
	fi
	for tool in du sort head awk sed; do type $tool > /dev/null 2>&1 || { printf -- "${cR}ERROR:${cZ} couldn't find ${cW}'%s'${cZ} which is required by this function.\n" "$tool"; return; }; done
	local SCANDIR=.
	[[ -n "$1" && -d "$1" ]] && SCANDIR=${1%/}
	du -cks "$SCANDIR"/*|sort -rn|head -11|sed 's/\t/:/g'|awk -F : '\
	{
		OSZ=$1;
		SZ=OSZ;
		UNIT="KiB";
		if(SZ > 1536) {
			SZ=SZ/1024;
			UNIT="MiB";
		}
		if(SZ > 1536) {
			SZ=SZ/1024;
			UNIT="GiB";
		}
		if(SZ > 1536) {
			SZ=SZ/1024;
			UNIT="TiB";
		}
		if(SZ > 1536) {
			SZ=SZ/1024;
			UNIT="PiB";
		}
		printf "%-5.3f %s", SZ, UNIT;
		if ($2 ~ /^total$/) {
			printf "\t'${cR}'%s'${cZ}'\n", $2
		} else {
			printf "\t'${cW}'%s'${cZ}'\n", $2
		}
	}'
}

let SOURCED=1
(return >/dev/null 2>&1) || let SOURCED=0

if ! ((SOURCED)); then
	ducks
fi

unset SOURCED
