#!/usr/bin/env bash
# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:

function rionice
{
	if [[ $- == *i* ]]; then
		declare -A _colors=(
			[cR]='\e[1;31m'  [cG]='\e[1;32m'  [cB]='\e[1;34m'
			[cR_]='\e[0;31m' [cG_]='\e[0;32m' [cB_]='\e[0;34m'
			[cW]='\e[1;37m'  [cY]='\e[1;33m'
			[cW_]='\e[0;37m' [cY_]='\e[0;33m'
			[cZ]='\e[0m'
		)
		for _k in "${!_colors[@]}"; do
			  declare -p "$_k" &>/dev/null || local "$_k"="${_colors[$_k]}"
		done
	fi
	for tool in ionice pgrep renice sudo; do type $tool > /dev/null 2>&1 || { printf -- "${cR}ERROR:${cZ} couldn't find ${cW}'%s'${cZ} which is required by this function.\n" "$tool"; return; }; done
	for procname in "$@"; do
		local -a PIDS=( $(pgrep "$procname") )
		if [[ -n "$PIDS" ]]; then
			printf "${cG}Process${cZ} [${cY}%s${cZ}]: ${cW}%s${cZ}\n" "$procname" "$pid"
			sudo bash -c "for pid in ${PIDS[*]}; do ( set -x; renice -n -10 -p \$pid; ionice -c 2 -p \$pid ); done"
		fi
	done
}
