# For a complete introduction, visit the official docs at: https://espanso.org/docs/
imports:
  - "_kaomoji.yml"
  - "_arrows.yml"
  - "_quotes.yml"
  - "_supsub.yml"
  - "_times.yml"
  - "_fullwidth.yml"
matches:
  # Personal stuff
  - trigger: ":mfg"
    label: "MFG, mit freundlichem Gruß"
    replace: "Mit freundlichem Gruß,\nOliver Schneider"
  - triggers: [ ":br",  ":wbr" ]
    label: "With best regards"
    replace: "With best regards,\nOliver Schneider"
  - triggers: [ ":rumfg", ":rusmfg", ":rubr", ":ruwbr" ]
    label: "С уважением"
    replace: "С уважением,\nОливер Шнайдер"
  - triggers: [ ":ellipsis" ]
    label: "Ellipsis …"
    replace: "…"
